openapi: 3.1.0
info:
  contact:
    email: blah+oapicf@cliffano.com
    name: Minecraft Versions
    url: https://github.com/oapicf/minecraft-versions
  description: SDK for Minecraft versions info
  license:
    name: MIT
  version: 1.2.1-pre.0
servers:
- url: https://launchermeta.mojang.com
- url: https://piston-meta.mojang.com
paths:
  /mc/game/version_manifest.json:
    get:
      operationId: get_minecraft_version_manifest
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VersionManifest"
          description: A list of Minecraft versions with the latest and snapshot releases
      summary: Get Minecraft version manifest
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /v1/packages/{packageId}/{versionId}.json:
    get:
      operationId: get_minecraft_version_package_info
      parameters:
      - example: 177e49d3233cb6eac42f0495c0a48e719870c2ae
        explode: false
        in: path
        name: packageId
        required: true
        schema:
          type: string
        style: simple
      - example: 1.21
        explode: false
        in: path
        name: versionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VersionPackageInfo"
          description: Get package version details
      summary: Get Minecraft version package info
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    VersionManifest:
      example:
        latest:
          release: 1.21
          snapshot: 24w14potato
        versions:
        - id: 24w14potato
          type: snapshot
          url: https://piston-meta.mojang.com/v1/packages/21df7f4ba484a6437ab5e9dca0b4dfb5dcefc802/24w14potato.json
          time: 2024-04-01T11:14:41.000+00:00
          releaseTime: 2024-04-01T11:07:19.000+00:00
        - id: 24w14potato
          type: snapshot
          url: https://piston-meta.mojang.com/v1/packages/21df7f4ba484a6437ab5e9dca0b4dfb5dcefc802/24w14potato.json
          time: 2024-04-01T11:14:41.000+00:00
          releaseTime: 2024-04-01T11:07:19.000+00:00
      properties:
        latest:
          $ref: "#/components/schemas/VersionManifest_latest"
        versions:
          items:
            $ref: "#/components/schemas/Version"
          title: versions
          type: array
          default: null
      title: VersionManifest
    Version:
      example:
        id: 24w14potato
        type: snapshot
        url: https://piston-meta.mojang.com/v1/packages/21df7f4ba484a6437ab5e9dca0b4dfb5dcefc802/24w14potato.json
        time: 2024-04-01T11:14:41.000+00:00
        releaseTime: 2024-04-01T11:07:19.000+00:00
      properties:
        id:
          example: 24w14potato
          title: id
          type: string
        type:
          example: snapshot
          title: type
          type: string
        url:
          example: https://piston-meta.mojang.com/v1/packages/21df7f4ba484a6437ab5e9dca0b4dfb5dcefc802/24w14potato.json
          title: url
          type: string
        time:
          example: 2024-04-01T11:14:41.000+00:00
          format: date-time
          title: time
          type: string
        releaseTime:
          example: 2024-04-01T11:07:19.000+00:00
          format: date-time
          title: releaseTime
          type: string
      title: Version
    VersionPackageInfo:
      example:
        version: version
        assetIndex:
          id: id
          sha1: sha1
          size: 0
          totalSize: 6
          url: url
        assets: assets
        complianceLevel: 1
        downloads:
          client:
            sha1: sha1
            size: 5
            url: url
          client_mappings:
            sha1: sha1
            size: 5
            url: url
          server:
            sha1: sha1
            size: 5
            url: url
          server_mappings:
            sha1: sha1
            size: 5
            url: url
        id: id
        javaVersion:
          component: component
          majorVersion: 5
        mainClass: net.minecraft.client.main.Main
        minimumLauncherVersion: 21
        time: 2024-04-01T11:14:41.000+00:00
        releaseTime: 2024-04-01T11:07:19.000+00:00
        type: snapshot
      properties:
        version:
          title: version
          type: string
        assetIndex:
          $ref: "#/components/schemas/VersionPackageInfo_assetIndex"
        assets:
          title: assets
          type: string
        complianceLevel:
          title: complianceLevel
          type: integer
        downloads:
          $ref: "#/components/schemas/VersionPackageInfo_downloads"
        id:
          title: id
          type: string
        javaVersion:
          $ref: "#/components/schemas/VersionPackageInfo_javaVersion"
        mainClass:
          example: net.minecraft.client.main.Main
          title: mainClass
          type: string
        minimumLauncherVersion:
          example: 21
          title: minimumLauncherVersion
          type: integer
        time:
          example: 2024-04-01T11:14:41.000+00:00
          format: date-time
          title: time
          type: string
        releaseTime:
          example: 2024-04-01T11:07:19.000+00:00
          format: date-time
          title: releaseTime
          type: string
        type:
          example: snapshot
          title: type
          type: string
      title: VersionPackageInfo
    Download:
      example:
        sha1: sha1
        size: 5
        url: url
      properties:
        sha1:
          title: sha1
          type: string
        size:
          title: size
          type: integer
        url:
          title: url
          type: string
      title: Download
    VersionManifest_latest:
      example:
        release: 1.21
        snapshot: 24w14potato
      properties:
        release:
          example: 1.21
          title: release
          type: string
        snapshot:
          example: 24w14potato
          title: snapshot
          type: string
      title: VersionManifest_latest
    VersionPackageInfo_assetIndex:
      example:
        id: id
        sha1: sha1
        size: 0
        totalSize: 6
        url: url
      properties:
        id:
          title: id
          type: string
        sha1:
          title: sha1
          type: string
        size:
          title: size
          type: integer
        totalSize:
          title: totalSize
          type: integer
        url:
          title: url
          type: string
      title: VersionPackageInfo_assetIndex
    VersionPackageInfo_downloads:
      example:
        client:
          sha1: sha1
          size: 5
          url: url
        client_mappings:
          sha1: sha1
          size: 5
          url: url
        server:
          sha1: sha1
          size: 5
          url: url
        server_mappings:
          sha1: sha1
          size: 5
          url: url
      properties:
        client:
          $ref: "#/components/schemas/Download"
        client_mappings:
          $ref: "#/components/schemas/Download"
        server:
          $ref: "#/components/schemas/Download"
        server_mappings:
          $ref: "#/components/schemas/Download"
      title: VersionPackageInfo_downloads
    VersionPackageInfo_javaVersion:
      example:
        component: component
        majorVersion: 5
      properties:
        component:
          title: component
          type: string
        majorVersion:
          title: majorVersion
          type: integer
      title: VersionPackageInfo_javaVersion
