openapi: 3.0.0
info:
  contact:
    email: blah+oapicf@cliffano.com
    name: Minecraft Versions
    url: https://github.com/oapicf/minecraft-versions
  description: SDK for Minecraft versions info
  license:
    name: MIT
  version: 0.9.0-pre.0
servers:
- url: https://launchermeta.mojang.com
- url: https://piston-meta.mojang.com
paths:
  /mc/game/version_manifest.json:
    get:
      operationId: getMinecraftVersionManifest
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionManifest'
          description: A list of Minecraft versions with the latest and snapshot releases
      summary: Get Minecraft version manifest
  /v1/packages/{packageId}/{versionId}.json:
    get:
      operationId: getMinecraftVersionPackageInfo
      parameters:
      - example: 177e49d3233cb6eac42f0495c0a48e719870c2ae
        explode: false
        in: path
        name: packageId
        required: true
        schema:
          type: string
        style: simple
      - example: 1.21
        explode: false
        in: path
        name: versionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionPackageInfo'
          description: Get package version details
      summary: Get Minecraft version package info
components:
  schemas:
    VersionManifest:
      example:
        versions:
        - releaseTime: 2024-04-01T11:07:19Z
          id: 24w14potato
          time: 2024-04-01T11:14:41Z
          type: snapshot
          url: https://piston-meta.mojang.com/v1/packages/21df7f4ba484a6437ab5e9dca0b4dfb5dcefc802/24w14potato.json
        - releaseTime: 2024-04-01T11:07:19Z
          id: 24w14potato
          time: 2024-04-01T11:14:41Z
          type: snapshot
          url: https://piston-meta.mojang.com/v1/packages/21df7f4ba484a6437ab5e9dca0b4dfb5dcefc802/24w14potato.json
        latest:
          release: "1.21"
          snapshot: 24w14potato
      properties:
        latest:
          $ref: '#/components/schemas/VersionManifest_latest'
        versions:
          items:
            $ref: '#/components/schemas/Version'
          title: versions
          type: array
      title: VersionManifest
      type: object
    Version:
      example:
        releaseTime: 2024-04-01T11:07:19Z
        id: 24w14potato
        time: 2024-04-01T11:14:41Z
        type: snapshot
        url: https://piston-meta.mojang.com/v1/packages/21df7f4ba484a6437ab5e9dca0b4dfb5dcefc802/24w14potato.json
      properties:
        id:
          example: 24w14potato
          title: id
          type: string
        type:
          example: snapshot
          title: type
          type: string
        url:
          example: https://piston-meta.mojang.com/v1/packages/21df7f4ba484a6437ab5e9dca0b4dfb5dcefc802/24w14potato.json
          title: url
          type: string
        time:
          example: 2024-04-01T11:14:41Z
          format: date-time
          title: time
          type: string
        releaseTime:
          example: 2024-04-01T11:07:19Z
          format: date-time
          title: releaseTime
          type: string
      title: Version
      type: object
    VersionPackageInfo:
      example:
        assets: assets
        releaseTime: 2024-04-01T11:07:19Z
        mainClass: net.minecraft.client.main.Main
        downloads:
          server:
            sha1: sha1
            size: 5
            url: url
          server_mappings:
            sha1: sha1
            size: 5
            url: url
          client:
            sha1: sha1
            size: 5
            url: url
          client_mappings:
            sha1: sha1
            size: 5
            url: url
        javaVersion:
          component: component
          majorVersion: 5
        complianceLevel: 1
        minimumLauncherVersion: 21
        assetIndex:
          sha1: sha1
          totalSize: 6
          size: 0
          id: id
          url: url
        id: id
        time: 2024-04-01T11:14:41Z
        type: snapshot
        version: version
      properties:
        version:
          title: version
          type: string
        assetIndex:
          $ref: '#/components/schemas/VersionPackageInfo_assetIndex'
        assets:
          title: assets
          type: string
        complianceLevel:
          title: complianceLevel
          type: integer
        downloads:
          $ref: '#/components/schemas/VersionPackageInfo_downloads'
        id:
          title: id
          type: string
        javaVersion:
          $ref: '#/components/schemas/VersionPackageInfo_javaVersion'
        mainClass:
          example: net.minecraft.client.main.Main
          title: mainClass
          type: string
        minimumLauncherVersion:
          example: 21
          title: minimumLauncherVersion
          type: integer
        time:
          example: 2024-04-01T11:14:41Z
          format: date-time
          title: time
          type: string
        releaseTime:
          example: 2024-04-01T11:07:19Z
          format: date-time
          title: releaseTime
          type: string
        type:
          example: snapshot
          title: type
          type: string
      title: VersionPackageInfo
      type: object
    Download:
      example:
        sha1: sha1
        size: 5
        url: url
      properties:
        sha1:
          title: sha1
          type: string
        size:
          title: size
          type: integer
        url:
          title: url
          type: string
      title: Download
      type: object
    VersionManifest_latest:
      example:
        release: "1.21"
        snapshot: 24w14potato
      properties:
        release:
          example: "1.21"
          title: release
          type: string
        snapshot:
          example: 24w14potato
          title: snapshot
          type: string
      title: VersionManifest_latest
      type: object
    VersionPackageInfo_assetIndex:
      example:
        sha1: sha1
        totalSize: 6
        size: 0
        id: id
        url: url
      properties:
        id:
          title: id
          type: string
        sha1:
          title: sha1
          type: string
        size:
          title: size
          type: integer
        totalSize:
          title: totalSize
          type: integer
        url:
          title: url
          type: string
      title: VersionPackageInfo_assetIndex
      type: object
    VersionPackageInfo_downloads:
      example:
        server:
          sha1: sha1
          size: 5
          url: url
        server_mappings:
          sha1: sha1
          size: 5
          url: url
        client:
          sha1: sha1
          size: 5
          url: url
        client_mappings:
          sha1: sha1
          size: 5
          url: url
      properties:
        client:
          $ref: '#/components/schemas/Download'
        client_mappings:
          $ref: '#/components/schemas/Download'
        server:
          $ref: '#/components/schemas/Download'
        server_mappings:
          $ref: '#/components/schemas/Download'
      title: VersionPackageInfo_downloads
      type: object
    VersionPackageInfo_javaVersion:
      example:
        component: component
        majorVersion: 5
      properties:
        component:
          title: component
          type: string
        majorVersion:
          title: majorVersion
          type: integer
      title: VersionPackageInfo_javaVersion
      type: object
